---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  annotations:
    container.apparmor.security.beta.kubernetes.io/carts-db: "localhost/k8s-apparmor-example-deny-write"
    container.apparmor.security.beta.kubernetes.io/app: "unconfined"
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsGroup: 0
      hostPID: true
      hostIPC: true
      hostNetwork: true
      hostAliases:
      - ip: "127.0.0.1"
        hostname: ["foo.bar"]
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: carts-db
        image: mongo:latest
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 15000
          capabilities:
            drop: ["NET_ADMIN", "SYS_TIME"]
        resources:
          limits:
            cpu: 24m
      - name: app
        image: app
        securityContext:
          runAsGroup: 0
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            memory: 24M
      initContainers:
      - name: carts-init
        image: mongo:1.28
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: 24M
